  services:
    parser:
      image: parseapp:latest
      restart: always
      environment:
        TIME_TO_SLEEP: 3600
        DB_USER: postgres
        DB_PASSWORD: 1234qwerty
        DB_PORT: 5432
        DB_HOST: db
        DB_NAME: beregDB
      ports:
        - '5000:5000'
    db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234qwerty
        POSTGRES_DB: beregDB
      ports:
        - '5432:5432'
