  services:
    db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234qwerty
        POSTGRES_DB: beregDB
      ports:
        - '5432:5432'
